---
- name: Make sure the EPEL repository is available
  template: >
    src=epel.repo 
    dest=/etc/yum.repos.d/epel.repo 
    owner=root group=root mode=644

- name: Make the Sensu repository is available
  template: >
    src=sensu.repo
    dest=/etc/yum.repos.d/sensu.repo
    owner=root group=root mode=644

- name: Install the Dependencies that are needed 
  yum: pkg={{ item }} state=installed
  with_items:
   - python-pip
   - python-devel
   - nagios-plugins-all
   - curl
   - openssl
   - python-zope-interface
   - libyaml
   - sysstat
   - ruby

- name: Install supervisord
  pip: name=supervisor state=present

- name: Install the sensu package
  yum: pkg=sensu state=installed

- name: Get the sensu gem Dependencies
  gem: name=sensu-plugin state=present
